FROM python:3.10

ENV PYTHONUNBUFFERED=1
ENV PYTHONDONTWRITEBYTECODE=1
ENV POETRY_VIRTUALENVS_CREATE=false

RUN pip install poetry

WORKDIR /app/
COPY poetry.lock pyproject.toml /app/

RUN poetry install --no-root

COPY ./ /app/

CMD ["python", "dnull_mqtt"]
